// FeCIM Array Verilog Netlist
// Generated by Module 6: FeCIM Design Suite
// Generated: 2026-02-01 20:53:32
// Operation Mode: Compute
// Array Size: 8 rows x 8 cols (64 cells)
// Architecture: passive
// Technology: SKY130
// Conductance Levels: 30
// Initial Weights: Pre-programmed from neural network

module fecim_crossbar (
    input  wire [7:0] WL,  // Word Lines (row select)
    inout  wire [7:0] BL,  // Bit Lines (column data)
    inout  wire       VPWR, // Power supply
    inout  wire       VGND  // Ground
);

    // Array parameters
    parameter ROWS = 8;
    parameter COLS = 8;
    parameter LEVELS = 30;
    parameter MODE = "Compute";
    parameter ARCHITECTURE = "passive";

    // FeCIM cell instances
    // Naming convention: R_{row}_{col}
    // Instance parameter: conductance level (0 to LEVELS-1)

    // Cell [0,0]: weight=0.1000, level=16, G=59.66 uS
    fecim_bit #(.LEVEL(16)) R_0_0 (
        .WL  (WL[0]),
        .BL  (BL[0]),
        .VPWR (VPWR),
        .VGND (VGND)
    );

    // Cell [0,1]: weight=-0.2000, level=11, G=44.14 uS
    fecim_bit #(.LEVEL(11)) R_0_1 (
        .WL  (WL[0]),
        .BL  (BL[1]),
        .VPWR (VPWR),
        .VGND (VGND)
    );

    // Cell [0,2]: weight=0.3000, level=19, G=68.97 uS
    fecim_bit #(.LEVEL(19)) R_0_2 (
        .WL  (WL[0]),
        .BL  (BL[2]),
        .VPWR (VPWR),
        .VGND (VGND)
    );

    // Cell [0,3]: weight=-0.4000, level=8, G=34.83 uS
    fecim_bit #(.LEVEL(8)) R_0_3 (
        .WL  (WL[0]),
        .BL  (BL[3]),
        .VPWR (VPWR),
        .VGND (VGND)
    );

    // Cell [0,4]: weight=0.5000, level=23, G=81.38 uS
    fecim_bit #(.LEVEL(23)) R_0_4 (
        .WL  (WL[0]),
        .BL  (BL[4]),
        .VPWR (VPWR),
        .VGND (VGND)
    );

    // Cell [0,5]: weight=-0.6000, level=5, G=25.52 uS
    fecim_bit #(.LEVEL(5)) R_0_5 (
        .WL  (WL[0]),
        .BL  (BL[5]),
        .VPWR (VPWR),
        .VGND (VGND)
    );

    // Cell [0,6]: weight=0.7000, level=26, G=90.69 uS
    fecim_bit #(.LEVEL(26)) R_0_6 (
        .WL  (WL[0]),
        .BL  (BL[6]),
        .VPWR (VPWR),
        .VGND (VGND)
    );

    // Cell [0,7]: weight=-0.8000, level=2, G=16.21 uS
    fecim_bit #(.LEVEL(2)) R_0_7 (
        .WL  (WL[0]),
        .BL  (BL[7]),
        .VPWR (VPWR),
        .VGND (VGND)
    );

    // Cell [1,0]: weight=-0.1000, level=13, G=50.34 uS
    fecim_bit #(.LEVEL(13)) R_1_0 (
        .WL  (WL[1]),
        .BL  (BL[0]),
        .VPWR (VPWR),
        .VGND (VGND)
    );

    // Cell [1,1]: weight=0.2000, level=18, G=65.86 uS
    fecim_bit #(.LEVEL(18)) R_1_1 (
        .WL  (WL[1]),
        .BL  (BL[1]),
        .VPWR (VPWR),
        .VGND (VGND)
    );

    // Cell [1,2]: weight=-0.3000, level=10, G=41.03 uS
    fecim_bit #(.LEVEL(10)) R_1_2 (
        .WL  (WL[1]),
        .BL  (BL[2]),
        .VPWR (VPWR),
        .VGND (VGND)
    );

    // Cell [1,3]: weight=0.4000, level=21, G=75.17 uS
    fecim_bit #(.LEVEL(21)) R_1_3 (
        .WL  (WL[1]),
        .BL  (BL[3]),
        .VPWR (VPWR),
        .VGND (VGND)
    );

    // Cell [1,4]: weight=-0.5000, level=6, G=28.62 uS
    fecim_bit #(.LEVEL(6)) R_1_4 (
        .WL  (WL[1]),
        .BL  (BL[4]),
        .VPWR (VPWR),
        .VGND (VGND)
    );

    // Cell [1,5]: weight=0.6000, level=24, G=84.48 uS
    fecim_bit #(.LEVEL(24)) R_1_5 (
        .WL  (WL[1]),
        .BL  (BL[5]),
        .VPWR (VPWR),
        .VGND (VGND)
    );

    // Cell [1,6]: weight=-0.7000, level=3, G=19.31 uS
    fecim_bit #(.LEVEL(3)) R_1_6 (
        .WL  (WL[1]),
        .BL  (BL[6]),
        .VPWR (VPWR),
        .VGND (VGND)
    );

    // Cell [1,7]: weight=0.8000, level=27, G=93.79 uS
    fecim_bit #(.LEVEL(27)) R_1_7 (
        .WL  (WL[1]),
        .BL  (BL[7]),
        .VPWR (VPWR),
        .VGND (VGND)
    );

    // Cell [2,0]: weight=0.1500, level=17, G=62.76 uS
    fecim_bit #(.LEVEL(17)) R_2_0 (
        .WL  (WL[2]),
        .BL  (BL[0]),
        .VPWR (VPWR),
        .VGND (VGND)
    );

    // Cell [2,1]: weight=-0.2500, level=10, G=41.03 uS
    fecim_bit #(.LEVEL(10)) R_2_1 (
        .WL  (WL[2]),
        .BL  (BL[1]),
        .VPWR (VPWR),
        .VGND (VGND)
    );

    // Cell [2,2]: weight=0.3500, level=20, G=72.07 uS
    fecim_bit #(.LEVEL(20)) R_2_2 (
        .WL  (WL[2]),
        .BL  (BL[2]),
        .VPWR (VPWR),
        .VGND (VGND)
    );

    // Cell [2,3]: weight=-0.4500, level=7, G=31.72 uS
    fecim_bit #(.LEVEL(7)) R_2_3 (
        .WL  (WL[2]),
        .BL  (BL[3]),
        .VPWR (VPWR),
        .VGND (VGND)
    );

    // Cell [2,4]: weight=0.5500, level=23, G=81.38 uS
    fecim_bit #(.LEVEL(23)) R_2_4 (
        .WL  (WL[2]),
        .BL  (BL[4]),
        .VPWR (VPWR),
        .VGND (VGND)
    );

    // Cell [2,5]: weight=-0.6500, level=4, G=22.41 uS
    fecim_bit #(.LEVEL(4)) R_2_5 (
        .WL  (WL[2]),
        .BL  (BL[5]),
        .VPWR (VPWR),
        .VGND (VGND)
    );

    // Cell [2,6]: weight=0.7500, level=27, G=93.79 uS
    fecim_bit #(.LEVEL(27)) R_2_6 (
        .WL  (WL[2]),
        .BL  (BL[6]),
        .VPWR (VPWR),
        .VGND (VGND)
    );

    // Cell [2,7]: weight=-0.8500, level=1, G=13.10 uS
    fecim_bit #(.LEVEL(1)) R_2_7 (
        .WL  (WL[2]),
        .BL  (BL[7]),
        .VPWR (VPWR),
        .VGND (VGND)
    );

    // Cell [3,0]: weight=-0.1500, level=12, G=47.24 uS
    fecim_bit #(.LEVEL(12)) R_3_0 (
        .WL  (WL[3]),
        .BL  (BL[0]),
        .VPWR (VPWR),
        .VGND (VGND)
    );

    // Cell [3,1]: weight=0.2500, level=19, G=68.97 uS
    fecim_bit #(.LEVEL(19)) R_3_1 (
        .WL  (WL[3]),
        .BL  (BL[1]),
        .VPWR (VPWR),
        .VGND (VGND)
    );

    // Cell [3,2]: weight=-0.3500, level=9, G=37.93 uS
    fecim_bit #(.LEVEL(9)) R_3_2 (
        .WL  (WL[3]),
        .BL  (BL[2]),
        .VPWR (VPWR),
        .VGND (VGND)
    );

    // Cell [3,3]: weight=0.4500, level=22, G=78.28 uS
    fecim_bit #(.LEVEL(22)) R_3_3 (
        .WL  (WL[3]),
        .BL  (BL[3]),
        .VPWR (VPWR),
        .VGND (VGND)
    );

    // Cell [3,4]: weight=-0.5500, level=6, G=28.62 uS
    fecim_bit #(.LEVEL(6)) R_3_4 (
        .WL  (WL[3]),
        .BL  (BL[4]),
        .VPWR (VPWR),
        .VGND (VGND)
    );

    // Cell [3,5]: weight=0.6500, level=25, G=87.59 uS
    fecim_bit #(.LEVEL(25)) R_3_5 (
        .WL  (WL[3]),
        .BL  (BL[5]),
        .VPWR (VPWR),
        .VGND (VGND)
    );

    // Cell [3,6]: weight=-0.7500, level=2, G=16.21 uS
    fecim_bit #(.LEVEL(2)) R_3_6 (
        .WL  (WL[3]),
        .BL  (BL[6]),
        .VPWR (VPWR),
        .VGND (VGND)
    );

    // Cell [3,7]: weight=0.8500, level=28, G=96.90 uS
    fecim_bit #(.LEVEL(28)) R_3_7 (
        .WL  (WL[3]),
        .BL  (BL[7]),
        .VPWR (VPWR),
        .VGND (VGND)
    );

    // Cell [4,0]: weight=0.0500, level=15, G=56.55 uS
    fecim_bit #(.LEVEL(15)) R_4_0 (
        .WL  (WL[4]),
        .BL  (BL[0]),
        .VPWR (VPWR),
        .VGND (VGND)
    );

    // Cell [4,1]: weight=-0.1500, level=12, G=47.24 uS
    fecim_bit #(.LEVEL(12)) R_4_1 (
        .WL  (WL[4]),
        .BL  (BL[1]),
        .VPWR (VPWR),
        .VGND (VGND)
    );

    // Cell [4,2]: weight=0.2500, level=19, G=68.97 uS
    fecim_bit #(.LEVEL(19)) R_4_2 (
        .WL  (WL[4]),
        .BL  (BL[2]),
        .VPWR (VPWR),
        .VGND (VGND)
    );

    // Cell [4,3]: weight=-0.3500, level=9, G=37.93 uS
    fecim_bit #(.LEVEL(9)) R_4_3 (
        .WL  (WL[4]),
        .BL  (BL[3]),
        .VPWR (VPWR),
        .VGND (VGND)
    );

    // Cell [4,4]: weight=0.4500, level=22, G=78.28 uS
    fecim_bit #(.LEVEL(22)) R_4_4 (
        .WL  (WL[4]),
        .BL  (BL[4]),
        .VPWR (VPWR),
        .VGND (VGND)
    );

    // Cell [4,5]: weight=-0.5500, level=6, G=28.62 uS
    fecim_bit #(.LEVEL(6)) R_4_5 (
        .WL  (WL[4]),
        .BL  (BL[5]),
        .VPWR (VPWR),
        .VGND (VGND)
    );

    // Cell [4,6]: weight=0.6500, level=25, G=87.59 uS
    fecim_bit #(.LEVEL(25)) R_4_6 (
        .WL  (WL[4]),
        .BL  (BL[6]),
        .VPWR (VPWR),
        .VGND (VGND)
    );

    // Cell [4,7]: weight=-0.7500, level=2, G=16.21 uS
    fecim_bit #(.LEVEL(2)) R_4_7 (
        .WL  (WL[4]),
        .BL  (BL[7]),
        .VPWR (VPWR),
        .VGND (VGND)
    );

    // Cell [5,0]: weight=-0.0500, level=14, G=53.45 uS
    fecim_bit #(.LEVEL(14)) R_5_0 (
        .WL  (WL[5]),
        .BL  (BL[0]),
        .VPWR (VPWR),
        .VGND (VGND)
    );

    // Cell [5,1]: weight=0.1500, level=17, G=62.76 uS
    fecim_bit #(.LEVEL(17)) R_5_1 (
        .WL  (WL[5]),
        .BL  (BL[1]),
        .VPWR (VPWR),
        .VGND (VGND)
    );

    // Cell [5,2]: weight=-0.2500, level=10, G=41.03 uS
    fecim_bit #(.LEVEL(10)) R_5_2 (
        .WL  (WL[5]),
        .BL  (BL[2]),
        .VPWR (VPWR),
        .VGND (VGND)
    );

    // Cell [5,3]: weight=0.3500, level=20, G=72.07 uS
    fecim_bit #(.LEVEL(20)) R_5_3 (
        .WL  (WL[5]),
        .BL  (BL[3]),
        .VPWR (VPWR),
        .VGND (VGND)
    );

    // Cell [5,4]: weight=-0.4500, level=7, G=31.72 uS
    fecim_bit #(.LEVEL(7)) R_5_4 (
        .WL  (WL[5]),
        .BL  (BL[4]),
        .VPWR (VPWR),
        .VGND (VGND)
    );

    // Cell [5,5]: weight=0.5500, level=23, G=81.38 uS
    fecim_bit #(.LEVEL(23)) R_5_5 (
        .WL  (WL[5]),
        .BL  (BL[5]),
        .VPWR (VPWR),
        .VGND (VGND)
    );

    // Cell [5,6]: weight=-0.6500, level=4, G=22.41 uS
    fecim_bit #(.LEVEL(4)) R_5_6 (
        .WL  (WL[5]),
        .BL  (BL[6]),
        .VPWR (VPWR),
        .VGND (VGND)
    );

    // Cell [5,7]: weight=0.7500, level=27, G=93.79 uS
    fecim_bit #(.LEVEL(27)) R_5_7 (
        .WL  (WL[5]),
        .BL  (BL[7]),
        .VPWR (VPWR),
        .VGND (VGND)
    );

    // Cell [6,0]: weight=0.2000, level=18, G=65.86 uS
    fecim_bit #(.LEVEL(18)) R_6_0 (
        .WL  (WL[6]),
        .BL  (BL[0]),
        .VPWR (VPWR),
        .VGND (VGND)
    );

    // Cell [6,1]: weight=-0.3000, level=10, G=41.03 uS
    fecim_bit #(.LEVEL(10)) R_6_1 (
        .WL  (WL[6]),
        .BL  (BL[1]),
        .VPWR (VPWR),
        .VGND (VGND)
    );

    // Cell [6,2]: weight=0.4000, level=21, G=75.17 uS
    fecim_bit #(.LEVEL(21)) R_6_2 (
        .WL  (WL[6]),
        .BL  (BL[2]),
        .VPWR (VPWR),
        .VGND (VGND)
    );

    // Cell [6,3]: weight=-0.5000, level=6, G=28.62 uS
    fecim_bit #(.LEVEL(6)) R_6_3 (
        .WL  (WL[6]),
        .BL  (BL[3]),
        .VPWR (VPWR),
        .VGND (VGND)
    );

    // Cell [6,4]: weight=0.6000, level=24, G=84.48 uS
    fecim_bit #(.LEVEL(24)) R_6_4 (
        .WL  (WL[6]),
        .BL  (BL[4]),
        .VPWR (VPWR),
        .VGND (VGND)
    );

    // Cell [6,5]: weight=-0.7000, level=3, G=19.31 uS
    fecim_bit #(.LEVEL(3)) R_6_5 (
        .WL  (WL[6]),
        .BL  (BL[5]),
        .VPWR (VPWR),
        .VGND (VGND)
    );

    // Cell [6,6]: weight=0.8000, level=27, G=93.79 uS
    fecim_bit #(.LEVEL(27)) R_6_6 (
        .WL  (WL[6]),
        .BL  (BL[6]),
        .VPWR (VPWR),
        .VGND (VGND)
    );

    // Cell [6,7]: weight=-0.9000, level=0, G=10.00 uS
    fecim_bit #(.LEVEL(0)) R_6_7 (
        .WL  (WL[6]),
        .BL  (BL[7]),
        .VPWR (VPWR),
        .VGND (VGND)
    );

    // Cell [7,0]: weight=-0.2000, level=11, G=44.14 uS
    fecim_bit #(.LEVEL(11)) R_7_0 (
        .WL  (WL[7]),
        .BL  (BL[0]),
        .VPWR (VPWR),
        .VGND (VGND)
    );

    // Cell [7,1]: weight=0.3000, level=19, G=68.97 uS
    fecim_bit #(.LEVEL(19)) R_7_1 (
        .WL  (WL[7]),
        .BL  (BL[1]),
        .VPWR (VPWR),
        .VGND (VGND)
    );

    // Cell [7,2]: weight=-0.4000, level=8, G=34.83 uS
    fecim_bit #(.LEVEL(8)) R_7_2 (
        .WL  (WL[7]),
        .BL  (BL[2]),
        .VPWR (VPWR),
        .VGND (VGND)
    );

    // Cell [7,3]: weight=0.5000, level=23, G=81.38 uS
    fecim_bit #(.LEVEL(23)) R_7_3 (
        .WL  (WL[7]),
        .BL  (BL[3]),
        .VPWR (VPWR),
        .VGND (VGND)
    );

    // Cell [7,4]: weight=-0.6000, level=5, G=25.52 uS
    fecim_bit #(.LEVEL(5)) R_7_4 (
        .WL  (WL[7]),
        .BL  (BL[4]),
        .VPWR (VPWR),
        .VGND (VGND)
    );

    // Cell [7,5]: weight=0.7000, level=26, G=90.69 uS
    fecim_bit #(.LEVEL(26)) R_7_5 (
        .WL  (WL[7]),
        .BL  (BL[5]),
        .VPWR (VPWR),
        .VGND (VGND)
    );

    // Cell [7,6]: weight=-0.8000, level=2, G=16.21 uS
    fecim_bit #(.LEVEL(2)) R_7_6 (
        .WL  (WL[7]),
        .BL  (BL[6]),
        .VPWR (VPWR),
        .VGND (VGND)
    );

    // Cell [7,7]: weight=0.9000, level=29, G=100.00 uS
    fecim_bit #(.LEVEL(29)) R_7_7 (
        .WL  (WL[7]),
        .BL  (BL[7]),
        .VPWR (VPWR),
        .VGND (VGND)
    );

endmodule
