// pkg/gui/tabs/export_all_tab.go
package tabs

import (
	"fmt"
	"os"
	"strings"
	"time"

	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/container"
	"fyne.io/fyne/v2/widget"

	"multilayer-ferroelectric-cim-visualizer/module6-eda/pkg/config"
	"multilayer-ferroelectric-cim-visualizer/module6-eda/pkg/export"
)

// MakeExportAllTab creates Tab 7: Export All
// One-click complete flow to generate all design files
func MakeExportAllTab(cfg *config.ArrayConfig) fyne.CanvasObject {
	// Progress tracking
	steps := []string{
		"Generate Cell Library (LEF/LIB/V)",
		"Generate Array Verilog",
		"Generate DEF Placement",
		"Generate SPICE Netlist",
		"Generate Design Data (JSON/CSV)",
		"Create OpenLane Config",
		"Validate All Files",
		"Package for Distribution",
	}

	stepLabels := make([]*widget.Label, len(steps))
	for i, step := range steps {
		stepLabels[i] = widget.NewLabel(fmt.Sprintf("⏸️ [%d] %s", i+1, step))
	}

	progressBar := widget.NewProgressBar()
	overallStatus := widget.NewLabel("")

	fileList := widget.NewMultiLineEntry()
	fileList.Disable()
	fileList.Wrapping = fyne.TextWrapOff

	// Run complete flow button
	runBtn := widget.NewButton("▶ RUN COMPLETE FLOW", func() {
		go func() {
			designName := fmt.Sprintf("fecim_crossbar_%dx%d", cfg.Rows, cfg.Cols)
			outputDir := fmt.Sprintf("output/%s", designName)
			os.MkdirAll(outputDir, 0755)
			os.MkdirAll(outputDir+"/cells", 0755)

			var files []string

			for i, label := range stepLabels {
				label.SetText(fmt.Sprintf("⏳ [%d] %s", i+1, steps[i]))
				progressBar.SetValue(float64(i) / float64(len(steps)))

				switch i {
				case 0: // Cell library
					cellCfg := config.DefaultCellConfig()
					lefContent := export.GenerateLEF(cellCfg)
					libContent := export.GenerateLiberty(cellCfg)
					vContent := export.GenerateCellVerilog(cellCfg)
					
					os.WriteFile(outputDir+"/cells/fecim_bitcell.lef", []byte(lefContent), 0644)
					os.WriteFile(outputDir+"/cells/fecim_bitcell.lib", []byte(libContent), 0644)
					os.WriteFile(outputDir+"/cells/fecim_bitcell.v", []byte(vContent), 0644)
					files = append(files, "cells/fecim_bitcell.lef", "cells/fecim_bitcell.lib", "cells/fecim_bitcell.v")

				case 1: // Array Verilog
					vContent := export.GenerateArrayVerilog(*cfg)
					os.WriteFile(outputDir+"/"+designName+".v", []byte(vContent), 0644)
					files = append(files, designName+".v")

				case 2: // DEF
					defContent := generateDEFContent(*cfg)
					os.WriteFile(outputDir+"/"+designName+".def", []byte(defContent), 0644)
					files = append(files, designName+".def")

				case 3: // SPICE (stub)
					spiceContent := fmt.Sprintf("* FeCIM Crossbar %dx%d SPICE Netlist\n* TODO: Add SPICE implementation\n", cfg.Rows, cfg.Cols)
					os.WriteFile(outputDir+"/"+designName+".sp", []byte(spiceContent), 0644)
					files = append(files, designName+".sp")

				case 4: // JSON (stub)
					jsonContent := fmt.Sprintf(`{"design": "%s", "rows": %d, "cols": %d}`, designName, cfg.Rows, cfg.Cols)
					os.WriteFile(outputDir+"/"+designName+".json", []byte(jsonContent), 0644)
					files = append(files, designName+".json")

				case 5: // OpenLane config
					configContent := export.GenerateOpenLaneConfig(*cfg)
					os.WriteFile(outputDir+"/config.json", []byte(configContent), 0644)
					files = append(files, "config.json")

				case 6: // Validate (placeholder)
					time.Sleep(100 * time.Millisecond)

				case 7: // Package
					readme := fmt.Sprintf(`# %s

Generated by FeCIM Design Suite
Date: %s

## Files

- cells/ - FeCIM bitcell library (LEF/LIB/V)
- %s.v - Verilog netlist
- %s.def - Physical placement
- config.json - OpenLane configuration

## Usage

1. Copy this directory to your OpenLane designs/
2. Run: flow.tcl -design %s
`, designName, time.Now().Format("2006-01-02"), designName, designName, designName)
					os.WriteFile(outputDir+"/README.md", []byte(readme), 0644)
					files = append(files, "README.md")
				}

				label.SetText(fmt.Sprintf("✅ [%d] %s", i+1, steps[i]))
				time.Sleep(200 * time.Millisecond) // Visual feedback
			}

			progressBar.SetValue(1.0)
			overallStatus.SetText("✅ COMPLETE - All files generated in " + outputDir)

			// Update file list
			var fileListStr strings.Builder
			fileListStr.WriteString(outputDir + "/\n")
			for _, f := range files {
				fileListStr.WriteString("  ├── " + f + "\n")
			}
			fileList.SetText(fileListStr.String())
		}()
	})

	// Steps container
	stepsContainer := container.NewVBox()
	for _, label := range stepLabels {
		stepsContainer.Add(label)
	}

	// Top section
	topSection := container.NewVBox(
		widget.NewLabel("Complete Export Pipeline"),
		widget.NewSeparator(),
		runBtn,
		progressBar,
		overallStatus,
		widget.NewSeparator(),
	)

	return container.NewBorder(
		topSection,
		nil,
		stepsContainer,
		nil,
		container.NewScroll(fileList),
	)
}

// generateDEFContent is a helper to generate DEF (duplicated from def_export_tab)
func generateDEFContent(cfg config.ArrayConfig) string {
	designName := fmt.Sprintf("fecim_crossbar_%dx%d", cfg.Rows, cfg.Cols)
	
	dbu := 1000
	cellWidthDBU := int(cfg.CellWidth * float64(dbu))
	cellHeightDBU := int(cfg.CellHeight * float64(dbu))
	
	margin := 1000
	dieWidth := cfg.Cols*cellWidthDBU + 2*margin
	dieHeight := cfg.Rows*cellHeightDBU + 2*margin
	
	var content strings.Builder
	content.WriteString(`VERSION 5.8 ;
DIVIDERCHAR "/" ;
BUSBITCHARS "[]" ;
`)
	content.WriteString(fmt.Sprintf("DESIGN %s ;\n", designName))
	content.WriteString(fmt.Sprintf("UNITS DISTANCE MICRONS %d ;\n\n", dbu))
	content.WriteString(fmt.Sprintf("DIEAREA ( 0 0 ) ( %d %d ) ;\n\n", dieWidth, dieHeight))
	
	totalCells := cfg.Rows * cfg.Cols
	content.WriteString(fmt.Sprintf("COMPONENTS %d ;\n", totalCells))
	
	for row := 0; row < cfg.Rows; row++ {
		for col := 0; col < cfg.Cols; col++ {
			x := margin + col*cellWidthDBU
			y := margin + row*cellHeightDBU
			content.WriteString(fmt.Sprintf("    - cell_%d_%d fecim_bitcell + FIXED ( %d %d ) N ;\n", row, col, x, y))
		}
	}
	content.WriteString("END COMPONENTS\n\n")
	
	numPins := cfg.Rows + cfg.Cols + 2
	content.WriteString(fmt.Sprintf("PINS %d ;\n", numPins))
	content.WriteString("    - VPWR + NET VPWR + DIRECTION INOUT + USE POWER ;\n")
	content.WriteString("    - VGND + NET VGND + DIRECTION INOUT + USE GROUND ;\n")
	for i := 0; i < cfg.Rows; i++ {
		content.WriteString(fmt.Sprintf("    - WL[%d] + NET WL[%d] + DIRECTION INPUT + USE SIGNAL ;\n", i, i))
	}
	for i := 0; i < cfg.Cols; i++ {
		content.WriteString(fmt.Sprintf("    - BL[%d] + NET BL[%d] + DIRECTION OUTPUT + USE SIGNAL ;\n", i, i))
	}
	content.WriteString("END PINS\n\n")
	
	content.WriteString("END DESIGN\n")
	return content.String()
}
