// pkg/export/magic_drc.go
// Magic layout tool script generators for DRC and SPICE extraction.
//
// Magic (http://opencircuitdesign.com/magic/) is the open-source layout editor
// used in the SKY130/GF180/IHP open PDK flows. It can:
//   - Run DRC (Design Rule Check) using PDK technology rules
//   - Extract SPICE netlists from layout (.ext → .spice) for LVS
//   - Generate GDS II from layout for tapeout
//
// FeCIM note: for purely educational abstract layouts (no transistor-level
// geometry), DRC is a sanity check only. Tapeout-ready cells require full
// transistor-level layout in Magic with foundry DRC sign-off.
//
// References:
//   Magic:  http://opencircuitdesign.com/magic/magic_docs.html
//   SKY130: magic -T sky130A.tech (via PDK_ROOT/sky130A/libs.tech/magic/)
//   IHP:    magic -T sg13g2.tech (via IHP_PDK_ROOT/ihp-sg13g2/libs.tech/magic/)
package export

import (
	"fmt"
	"strings"
	"time"

	"fecim-lattice-tools/module6-eda/pkg/config"
)

// GenerateMagicDRCScript returns a bash script that invokes Magic in batch mode
// to run DRC on the FeCIM cell layout.
//
// The script:
//  1. Loads the PDK technology file (sky130A.tech or sg13g2.tech)
//  2. Reads the layout file (.mag or .gds)
//  3. Runs DRC and reports violations
//  4. Exits non-zero on DRC errors
func GenerateMagicDRCScript(cfg config.ArrayConfig) string {
	designName := fmt.Sprintf("fecim_crossbar_%dx%d", cfg.Rows, cfg.Cols)
	cellName := cellNameFromArch(cfg.Architecture)
	tech := strings.ToLower(cfg.Technology)

	var techFile, pdkEnv string
	switch {
	case strings.Contains(tech, "gf180"):
		techFile = "${PDK_ROOT}/gf180mcuD/libs.tech/magic/gf180mcuD.tech"
		pdkEnv = "PDK_ROOT"
	case strings.Contains(tech, "ihp") || strings.Contains(tech, "sg13"):
		techFile = "${IHP_PDK_ROOT}/ihp-sg13g2/libs.tech/magic/sg13g2.tech"
		pdkEnv = "IHP_PDK_ROOT"
	default: // sky130
		techFile = "${PDK_ROOT}/sky130A/libs.tech/magic/sky130A.tech"
		pdkEnv = "PDK_ROOT"
	}

	return fmt.Sprintf(`#!/usr/bin/env bash
# FeCIM Magic DRC Script
# Generated: %s
# Array: %dx%d, Architecture: %s, Technology: %s
#
# Runs Magic DRC (Design Rule Check) on the FeCIM cell layout.
# DRC errors must be resolved before tapeout.
#
# Prerequisites:
#   - magic installed (apt: magic, or build from source)
#   - PDK technology file available (set %s env var)
#   - Layout file: cells/%s/%s.mag (Magic layout format)
#   - OR GDS file:  cells/%s/%s.gds (for GDS-based DRC)
#
# Usage:
#   export %s=/path/to/pdk
#   bash run_drc.sh
#
# NOTE: This is for abstract/educational layouts. Production tapeout requires
# full transistor-level layout with foundry DRC sign-off.

set -e

CELL="%s"
DESIGN="%s"
TECH_FILE="%s"
MAG_FILE="cells/${CELL}/${CELL}.mag"
GDS_FILE="cells/${CELL}/${CELL}.gds"
DRC_LOG="output/drc_report.txt"

echo "=== FeCIM Magic DRC ==="
echo "Cell:      ${CELL}"
echo "Design:    ${DESIGN}"
echo "Tech file: ${TECH_FILE}"
echo ""

# Check that PDK tech file is available
if [[ ! -f "${TECH_FILE}" ]]; then
    echo "WARNING: PDK tech file not found: ${TECH_FILE}"
    echo "  For SKY130: export PDK_ROOT=~/.volare && volare enable --pdk sky130 sky130A"
    echo "  For IHP:    export IHP_PDK_ROOT=~/ihp-sg13g2-pdk"
    echo "  Falling back to generic DRC (no foundry rules)"
    TECH_FILE=""
fi

mkdir -p output

# Prefer .mag layout; fall back to .gds
if [[ -f "${MAG_FILE}" ]]; then
    INPUT_FILE="${MAG_FILE}"
    INPUT_FORMAT="mag"
elif [[ -f "${GDS_FILE}" ]]; then
    INPUT_FILE="${GDS_FILE}"
    INPUT_FORMAT="gds"
else
    echo "WARNING: No layout file found (${MAG_FILE} or ${GDS_FILE})"
    echo "  The abstract LEF/GDS stub from module6 is sufficient for P&R"
    echo "  Full DRC requires transistor-level Magic layout."
    echo ""
    echo "Educational DRC skip: abstract FeCIM layout has no transistor geometry."
    echo "  For full DRC: create transistor-level layout in Magic, then run:"
    echo "  magic -T ${TECH_FILE:-sky130A} -rcfile magicrc cells/${CELL}/${CELL}.mag"
    exit 0
fi

echo "Running Magic DRC on: ${INPUT_FILE}"

# Run Magic in batch mode with Tcl DRC script
# Unquoted heredoc: bash expands ${INPUT_FILE}; Tcl vars (drc_count) are escaped as \$
magic -T "${TECH_FILE:-sky130A}" -noc -dnull << EOF
drc on
load ${INPUT_FILE}
drc check
set drc_count [drc list count total]
puts "DRC violations: \${drc_count}"
if {\${drc_count} > 0} {
    puts "=== DRC Errors ==="
    drc listall why
}
quit
EOF

echo ""
echo "DRC check complete — see output for violations."
echo "Report: ${DRC_LOG}"
`, time.Now().Format("2006-01-02"),
		cfg.Rows, cfg.Cols, cfg.Architecture, cfg.Technology,
		pdkEnv,
		cellName, cellName,
		cellName, cellName,
		pdkEnv,
		cellName, designName, techFile)
}

// GenerateMagicExtractionScript returns a bash script that uses Magic to extract
// a SPICE netlist from the FeCIM cell layout for LVS.
//
// The extracted SPICE file is used by netgen LVS to compare against the
// schematic netlist generated by module6 export.
func GenerateMagicExtractionScript(cfg config.CellConfig) string {
	cellName := cfg.Name
	if cellName == "" {
		cellName = "fecim_bitcell"
	}
	switch strings.ToLower(cfg.CellType) {
	case "1t1r":
		if cellName == "fecim_bitcell" {
			cellName = "fecim_1t1r_bitcell"
		}
	case "2t1r":
		if cellName == "fecim_bitcell" {
			cellName = "fecim_2t1r_bitcell"
		}
	}

	tech := strings.ToLower(cfg.Technology)
	var techFile string
	switch {
	case strings.Contains(tech, "gf180"):
		techFile = "${PDK_ROOT}/gf180mcuD/libs.tech/magic/gf180mcuD.tech"
	case strings.Contains(tech, "ihp") || strings.Contains(tech, "sg13"):
		techFile = "${IHP_PDK_ROOT}/ihp-sg13g2/libs.tech/magic/sg13g2.tech"
	default:
		techFile = "${PDK_ROOT}/sky130A/libs.tech/magic/sky130A.tech"
	}

	return fmt.Sprintf(`#!/usr/bin/env bash
# FeCIM Magic SPICE Extraction Script
# Generated: %s
# Cell: %s (type: %s, technology: %s)
#
# Extracts a SPICE netlist from the Magic layout for use in netgen LVS.
#
# Flow:
#   1. Load Magic layout (.mag)
#   2. Extract parasitic RC (.ext files)
#   3. Convert to SPICE (.spice) for LVS
#
# The output cells/%s/%s_ext.spice is used by run_lvs.sh

set -e

CELL="%s"
TECH_FILE="%s"
MAG_DIR="cells/${CELL}"
EXT_OUT="cells/${CELL}/${CELL}_ext.spice"

echo "=== FeCIM Magic SPICE Extraction ==="
echo "Cell:     ${CELL}"
echo "Tech:     ${TECH_FILE}"
echo "Output:   ${EXT_OUT}"
echo ""

mkdir -p "cells/${CELL}"

if [[ ! -f "cells/${CELL}/${CELL}.mag" ]]; then
    echo "ERROR: Magic layout not found: cells/${CELL}/${CELL}.mag"
    echo "  Full transistor-level layout required for extraction."
    exit 1
fi

# Run Magic extraction
magic -T "${TECH_FILE}" -noc -dnull -rcfile magicrc << EOF
load cells/${CELL}/${CELL}
extract all
ext2spice lvs
ext2spice -o ${EXT_OUT}
quit
EOF

echo "Extracted: ${EXT_OUT}"
echo "Next step: Run netgen LVS with: bash run_lvs.sh"
`, time.Now().Format("2006-01-02"),
		cellName, cfg.CellType, cfg.Technology,
		cellName, cellName,
		cellName, techFile)
}
