// pkg/export/netgen.go
// Netgen LVS (Layout vs. Schematic) script generators for FeCIM cells.
//
// Netgen is the open-source LVS tool used in the SKY130/GF180/IHP open PDK flows.
// It compares SPICE netlists (schematic vs. extracted layout) to verify equivalence.
//
// For FeCIM cells with no transistors (passive 0T1R), LVS is reduced to checking
// that the extracted RC netlist has the correct number of two-terminal devices.
// For 1T1R/2T1R cells with select transistors, full LVS verifies MOSFET connectivity.
//
// References:
//   Netgen: https://github.com/RTimothyEdwards/netgen
//   netgen -batch lvs command: http://opencircuitdesign.com/netgen/
//   SKY130 netgen setup: $PDK_ROOT/sky130A/libs.tech/netgen/sky130A_setup.tcl
package export

import (
	"fmt"
	"strings"
	"time"

	"fecim-lattice-tools/module6-eda/pkg/config"
)

// GenerateNetgenLVSScript returns a bash script that invokes netgen in batch mode
// to compare a schematic SPICE netlist against an extracted layout netlist.
//
// The generated script handles three architectures:
//   - passive (0T1R): pure resistive comparison
//   - 1t1r: NMOS selector + FeCap
//   - 2t1r: dual NMOS + FeCap
//
// Usage of the generated script:
//
//	bash run_lvs.sh
//
// Or invoke netgen directly:
//
//	netgen -batch lvs "{schematic.spice} {cell}" "{layout.spice} {cell}" \
//	  {setup.tcl} lvs_report.txt -json
func GenerateNetgenLVSScript(cfg config.CellConfig) string {
	cellName := cfg.Name
	if cellName == "" {
		cellName = "fecim_bitcell"
	}
	switch strings.ToLower(cfg.CellType) {
	case "1t1r":
		if cellName == "fecim_bitcell" {
			cellName = "fecim_1t1r_bitcell"
		}
	case "2t1r":
		if cellName == "fecim_bitcell" {
			cellName = "fecim_2t1r_bitcell"
		}
	}

	tech := strings.ToLower(cfg.Technology)
	if tech == "" {
		tech = "sky130"
	}
	var setupTCL string
	switch {
	case strings.Contains(tech, "gf180"):
		setupTCL = "${PDK_ROOT}/gf180mcuD/libs.tech/netgen/gf180mcu_setup.tcl"
	case strings.Contains(tech, "ihp") || strings.Contains(tech, "sg13"):
		setupTCL = "${IHP_PDK_ROOT}/ihp-sg13g2/libs.tech/netgen/sg13g2_setup.tcl"
	default: // sky130
		setupTCL = "${PDK_ROOT}/sky130A/libs.tech/netgen/sky130A_setup.tcl"
	}

	return fmt.Sprintf(`#!/usr/bin/env bash
# FeCIM Netgen LVS Script
# Generated: %s
# Cell: %s (architecture: %s, technology: %s)
#
# Compares schematic SPICE netlist (from circuit design) against
# extracted layout netlist (from Magic extraction or OpenROAD).
#
# Prerequisites:
#   - netgen installed (apt: netgen-lvs, or build from source)
#   - Schematic SPICE: cells/%s/%s.spice  (generated by module6 export)
#   - Layout SPICE:    cells/%s/%s_ext.spice (from Magic .ext → .spice)
#   - PDK setup TCL:   %s
#
# Usage:
#   bash run_lvs.sh
#
# Or run netgen directly:
#   netgen -batch lvs "{cells/%s/%s.spice} {%s}" \
#       "{cells/%s/%s_ext.spice} {%s}" \
#       %s lvs_report.txt -json
#
# LVS PASS means layout matches schematic — safe to tapeout.
# LVS FAIL means connectivity mismatch — must be fixed before tapeout.

set -e

CELL="%s"
SCHEMATIC="cells/${CELL}/${CELL}.spice"
LAYOUT="cells/${CELL}/${CELL}_ext.spice"
SETUP_TCL="%s"
REPORT="output/lvs_report.txt"
JSON_REPORT="output/lvs_report.json"

echo "=== FeCIM Netgen LVS ==="
echo "Cell:       ${CELL}"
echo "Schematic:  ${SCHEMATIC}"
echo "Layout:     ${LAYOUT}"
echo "Setup TCL:  ${SETUP_TCL}"
echo ""

# Verify inputs exist
if [[ ! -f "${SCHEMATIC}" ]]; then
    echo "ERROR: Schematic not found: ${SCHEMATIC}"
    echo "  Generate with: fecim-lattice-tools eda cli --spice"
    exit 1
fi
if [[ ! -f "${LAYOUT}" ]]; then
    echo "WARNING: Layout SPICE not found: ${LAYOUT}"
    echo "  Extract from Magic: magic -T ${SETUP_TCL} -rcfile magicrc"
    echo "  Then: extract all; ext2spice -r ${CELL}; ext2spice"
    echo "  Skipping LVS (layout extraction required for real LVS)."
    exit 0
fi
if [[ ! -f "${SETUP_TCL}" ]]; then
    echo "WARNING: PDK setup TCL not found: ${SETUP_TCL}"
    echo "  Using netgen without PDK device definitions."
    SETUP_TCL=""
fi

# Create output directory
mkdir -p output

# Run LVS
echo "Running netgen LVS..."
if [[ -n "${SETUP_TCL}" ]]; then
    netgen -batch lvs \
        "${SCHEMATIC} {${CELL}}" \
        "${LAYOUT} {${CELL}}" \
        "${SETUP_TCL}" \
        "${REPORT}" \
        -json 2>&1 | tee output/lvs_netgen.log
else
    netgen -batch lvs \
        "${SCHEMATIC} {${CELL}}" \
        "${LAYOUT} {${CELL}}" \
        "${REPORT}" \
        -json 2>&1 | tee output/lvs_netgen.log
fi

# Check result
if grep -q "Cells match uniquely" "${REPORT}" 2>/dev/null; then
    echo ""
    echo "✓ LVS PASSED: Layout matches schematic"
    echo "  Report: ${REPORT}"
elif grep -q "NET MISMATCH\|DEVICE MISMATCH\|Errors" "${REPORT}" 2>/dev/null; then
    echo ""
    echo "✗ LVS FAILED: Layout does not match schematic"
    echo "  Check report: ${REPORT}"
    exit 1
else
    echo ""
    echo "⚠ LVS result unclear — check: ${REPORT}"
fi
`, time.Now().Format("2006-01-02"),
		cellName, cfg.CellType, cfg.Technology,
		cellName, cellName,
		cellName, cellName,
		setupTCL,
		cellName, cellName, cellName,
		cellName, cellName, cellName,
		setupTCL,
		cellName, setupTCL)
}

// GenerateNetgenLVSTCL returns a standalone Tcl script for netgen batch LVS.
// This is the Tcl-level invocation that netgen runs internally.
// Useful for automation pipelines that invoke netgen via its Tcl interface.
func GenerateNetgenLVSTCL(cfg config.CellConfig) string {
	cellName := cfg.Name
	if cellName == "" {
		cellName = "fecim_bitcell"
	}
	switch strings.ToLower(cfg.CellType) {
	case "1t1r":
		if cellName == "fecim_bitcell" {
			cellName = "fecim_1t1r_bitcell"
		}
	case "2t1r":
		if cellName == "fecim_bitcell" {
			cellName = "fecim_2t1r_bitcell"
		}
	}

	return fmt.Sprintf(`# FeCIM Netgen LVS Tcl Script
# Generated: %s
# Cell: %s
#
# Usage (run from netgen batch mode):
#   netgen -batch source netgen_lvs.tcl
#
# Or from within netgen interactive shell:
#   source netgen_lvs.tcl

set cell "%s"
set schem "cells/${cell}/${cell}.spice"
set layout "cells/${cell}/${cell}_ext.spice"
set report "output/lvs_report"

# Read schematic netlist
puts "Reading schematic: $schem"
readnet spice $schem

# Read layout netlist (from Magic extraction)
puts "Reading layout:    $layout"
readnet spice $layout

# Run LVS comparison
puts "Running LVS..."
lvs "$schem $cell" "$layout $cell" $report

# Report outcome
if {[catch {
    set f [open ${report}.out r]
    set content [read $f]
    close $f
    if {[string match "*Cells match uniquely*" $content]} {
        puts "LVS PASSED: layout matches schematic"
    } else {
        puts "LVS FAILED: check ${report}.out"
    }
} err]} {
    puts "LVS complete — check output files"
}
`, time.Now().Format("2006-01-02"), cellName, cellName)
}
