// pkg/export/spice.go
package export

import (
	"fmt"
	"os"
	"strings"

	"fecim-lattice-tools/module6-eda/pkg/compiler"
	"fecim-lattice-tools/shared/logging"
)

var logSPICE = logging.NewLogger("eda-export-spice")

// GenerateSPICE creates ngspice-compatible netlist.
// Works with all operation modes (Storage, Memory, Compute).
func GenerateSPICE(design *compiler.ArrayDesign, vdd float64) string {
	logSPICE.Input("GenerateSPICE", map[string]interface{}{
		"mode":        design.Config.Mode,
		"totalCells":  design.Stats.TotalCells,
		"activeCells": design.Stats.ActiveCells,
		"vdd":         vdd,
	})

	var sb strings.Builder

	// Filter cells to export
	cellsToExport := filterActiveCells(design)

	sb.WriteString("* FeCIM Array SPICE Netlist\n")
	sb.WriteString("* Generated by Module 6: FeCIM Design Suite\n")
	sb.WriteString(fmt.Sprintf("* Operation Mode: %s\n", design.Config.Mode))
	sb.WriteString(fmt.Sprintf("* Array: %d cells\n\n", len(cellsToExport)))

	// Power supply
	sb.WriteString(fmt.Sprintf(".param VDD = %.2f\n", vdd))
	sb.WriteString("VDD vdd 0 DC {VDD}\n\n")

	// Find array dimensions from cells to export
	maxRow, maxCol := findCellDimensions(cellsToExport)

	// Word line drivers (inputs)
	sb.WriteString("* Word Line Drivers\n")
	for row := 0; row <= maxRow; row++ {
		sb.WriteString(fmt.Sprintf("VWL%d wl%d 0 DC 0\n", row, row))
	}
	sb.WriteString("\n")

	// Bit line loads
	sb.WriteString("* Bit Line Loads (1k for sensing)\n")
	for col := 0; col <= maxCol; col++ {
		sb.WriteString(fmt.Sprintf("RBL%d bl%d 0 1k\n", col, col))
	}
	sb.WriteString("\n")

	// FeFET cells as resistors (simplified model)
	sb.WriteString("* FeFET Cells (resistor model: R = 1/G)\n")
	for _, cell := range cellsToExport {
		// Use Resistance field if set, otherwise calculate from Conductance
		resistance := cell.Resistance
		if resistance == 0 && cell.Conductance > 0 {
			resistance = 1e6 / cell.Conductance // Ω from μS
		}
		sb.WriteString(fmt.Sprintf("R_%d_%d wl%d bl%d %.2f\n",
			cell.Row, cell.Col, cell.Row, cell.Col, resistance))
	}
	sb.WriteString("\n")

	// Analysis
	sb.WriteString("* Analysis\n")
	sb.WriteString(".op\n")
	sb.WriteString(".control\n")
	sb.WriteString("run\n")
	for col := 0; col <= maxCol; col++ {
		sb.WriteString(fmt.Sprintf("print i(RBL%d)\n", col))
	}
	sb.WriteString(".endc\n")
	sb.WriteString(".end\n")

	netlist := sb.String()

	logSPICE.Calculation("GenerateSPICE", map[string]interface{}{
		"cellsExported": len(cellsToExport),
		"wordLines":     maxRow + 1,
		"bitLines":      maxCol + 1,
		"netlistSize":   len(netlist),
	}, nil)

	return netlist
}

// ExportSPICE writes netlist to file.
// Works with all operation modes (Storage, Memory, Compute).
func ExportSPICE(design *compiler.ArrayDesign, path string, vdd float64) error {
	logSPICE.Input("ExportSPICE", map[string]interface{}{
		"path": path,
		"vdd":  vdd,
	})

	content := GenerateSPICE(design, vdd)

	err := os.WriteFile(path, []byte(content), 0644)
	if err != nil {
		logSPICE.ErrorContext("ExportSPICE", err, map[string]interface{}{
			"path": path,
		})
		return err
	}

	logSPICE.Debug("ExportSPICE: Exported netlist to %s (size: %d bytes)", path, len(content))

	return nil
}
